### ISSUE TITLE
视频导出闪退，选择的视频无法预览

### ISSUE THREAD

**Issue by chengkaizone** [galis/OpenTikTok#13]
android.media.MediaCodec$CodecException: Error 0xffffffc3
at android.media.MediaCodec.native_configure(Native Method)
at android.media.MediaCodec.configure(MediaCodec.java:2176)
at android.media.MediaCodec.configure(MediaCodec.java:2092)
at com.galix.avcore.util.Mp4Composite.openEncodeStream(Mp4Composite.java:125)
at com.galix.avcore.util.Mp4Composite.access$700(Mp4Composite.java:51)
at com.galix.avcore.util.Mp4Composite$7.run(Mp4Composite.java:400)

**Comment by ivlucks** [comment]
ui线程问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月4日(周日) 上午10:27
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [galis/OpenTikTok] 视频导出闪退，选择的视频无法预览 (Issue #13)




 
android.media.MediaCodec$CodecException: Error 0xffffffc3
 at android.media.MediaCodec.native_configure(Native Method)
 at android.media.MediaCodec.configure(MediaCodec.java:2176)
 at android.media.MediaCodec.configure(MediaCodec.java:2092)
 at com.galix.avcore.util.Mp4Composite.openEncodeStream(Mp4Composite.java:125)
 at com.galix.avcore.util.Mp4Composite.access$700(Mp4Composite.java:51)
 at com.galix.avcore.util.Mp4Composite$7.run(Mp4Composite.java:400)

**Comment by chengkaizone** [comment]
希望能完善下，我测试demo中的功能很多还未实现，同时支持编辑中的视频可实时预览
感谢感谢~

**Comment by ivlucks** [comment]
我对pag感兴趣，竟然不能运行😂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月4日(周日) 上午10:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [galis/OpenTikTok] 视频导出闪退，选择的视频无法预览 (Issue #13)




 
希望能完善下，我测试demo中的功能很多还未实现，同时支持编辑中的视频可实时预览
 感谢感谢~

**Comment by galis** [comment]
好的。还在维护，最近项目比较忙。

**Comment by liudoge66** [comment]
我在模拟器导出的时候没有问题，但是在导入到真机使用的时候出现了问题，报错信息同样是android.media.MediaCodec$CodecException: Error 0xffffffc3
搜索资料，可以知道是因为兼容性的问题 https://blog.csdn.net/weixin_43911199/article/details/129097371
一一排查后可得知是这一条语句的不兼容
mediaFormat.setInteger(MediaFormat.KEY_COLOR_FORMAT, MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV420PackedPlanar);
我们把它改成
mediaFormat.setInteger(MediaFormat.KEY_COLOR_FORMAT, MediaCodecInfo.CodecCapabilities.COLOR_FormatSurface);
应该就可以解决导出闪退的问题了
具体原理不明，可能是和各个厂商支持的手机色彩空间格式有关
