### ISSUE TITLE
开始制作，选择视频文件后报错，录屏也报错

### ISSUE THREAD

**Issue by fansangg** [galis/OpenTikTok#2]
项目运行后，开始制作点击后报错

 ```
java.lang.NullPointerException: Attempt to get length of null array
        at com.galix.opentiktok.ui.VideoPickActivity.lambda$onCreate$2$VideoPickActivity(VideoPickActivity.java:141)
```

加入非空判断后，读不到sd卡下的.mp4结尾文件，选择cache/composite下的视频文件后报这个错误

 ```
java.lang.NoSuchMethodError: No interface method getCurrentWindowMetrics()Landroid/view/WindowMetrics; in class Landroid/view/WindowManager; or its super classes (declaration of 'android.view.WindowManager' appears in /system/framework/framework.jar!classes3.dex)
        at com.galix.opentiktok.ui.VideoEditActivity.calCanvasSize(VideoEditActivity.java:369)
        at com.galix.opentiktok.ui.VideoEditActivity.onCreate(VideoEditActivity.java:289)
```

屏幕录制点击报错

```
2022-03-31 18:29:08.580 17579-18084/com.galix.opentiktok E/ClearFileSource: Failed to open file '/sdcard/coach.mp4'. (Permission denied)
2022-03-31 18:29:08.580 17579-18084/com.galix.opentiktok E/ClearFileSource: Failed to open file '/sdcard/testplayer.mp4'. (Permission denied)
2022-03-31 18:29:08.581 17579-18084/com.galix.opentiktok E/ClearFileSource: Failed to open file '/sdcard/coach.mp4'. (Permission denied)
2022-03-31 18:29:08.585 1674-2412/? E/WindowManager: App trying to use insecure INPUT_FEATURE_NO_INPUT_CHANNEL flag. Ignoring
2022-03-31 18:29:08.591 2543-3029/? E/DollieAdapterService: notifyActivityState pkg:com.galix.opentiktok/com.galix.opentiktok.dp.GameActivity state:2 fg:true mUid:10508
2022-03-31 18:29:08.591 2543-3029/? E/Booster_MatterAppRecommend: [isMatterPackage]invalid mMatterPackagesConfig
2022-03-31 18:29:08.606 2543-27585/? E/HsmCoreServiceImpl: onTransact in code is: 102
2022-03-31 18:29:08.635 1674-1725/? E/WindowManager: icon is null!!
2022-03-31 18:29:08.639 1674-1725/? E/WindowManager: icon is null!!
2022-03-31 18:29:08.642 17579-18084/com.galix.opentiktok E/GLUtil: Shader error: 0:27: S0001: 'texture' is not a function
    #version 300 es
    #extension GL_OES_EGL_image_external_essl3 : require
    #ifdef GL_ES
    #ifdef GL_FRAGMENT_PRECISION_HIGH
    precision highp float;
    #else
    precision mediump float;
    #endif
    #else
    #define highp
    #define mediump
    #define lowp
    #endif
    in vec2 vTextureCoord;
    in vec2 vlutTextureCoord;
    out vec4 vFragColor;
    uniform sampler2D inputImageTexture;
    uniform samplerExternalOES inputImageOesTexture;
    uniform sampler2D lutTexture;
    uniform float alpha;
    uniform bool isOes;
    
    vec4 filterTexture2D(sampler2D texture, vec2 coord){
        if (coord.x < 0.0||coord.x>1.0||coord.y<0.0||coord.y>1.0) {
            return vec4(0.0);
        }
        return texture(texture, coord);
    }
    
    void main(){
        highp vec3 srcNoOes = texture(inputImageTexture, vTextureCoord).rgb;
        highp vec3 srcOes = texture(inputImageOesTexture, vTextureCoord).rgb;
        highp vec3 src = isOes?srcOes:srcNoOes;
        highp float blueColor = src.b * 63.0;
        highp vec2 quad1;
        quad1.y = floor(floor(blueColor) / 8.0);
        quad1.x = floor(blueColor) - (quad1.y * 8.0);
        highp vec2 quad2;
        quad2.y = floor(ceil(blueColor) / 8.0);
        quad2.x = ceil(blueColor) - (quad2.y * 8.0);
        highp vec2 texPos1;
        texPos1.x = (quad1.x * 0.125) + 0.5/512.0 + ((0.125 - 1.0/512.0) * src.r);
        texPos1.y = (quad1.y * 0.125) + 0.5/512.0 + ((0.125 - 1.0/512.0) * src.g);
        vec2 texPos2;
        texPos2.x = (quad2.x * 0.125) + 0.5/512.0 + ((0.125 - 1.0/512.0) * src.r);
        texPos2.y = (quad2.y * 0.125) + 0.5/512.0 + ((0.125 - 1.0/512.0) * src.g);
    
        highp vec4 newColor1 = texture(lutTexture, texPos1);
        highp vec4 newColor2 = texture(lutTexture, texPos2);
        highp vec4 newColor = mix(newColor1, newColor2, fract(blueColor));
        vFragColor = vec4(newColor.rgb, 1.0);
    }
2022-03-31 18:29:08.642 17579-18084/com.galix.opentiktok E/GLUtil: Error compiling program: Link failed because of missing fragment shader.
2022-03-31 18:29:08.643 17579-18084/com.galix.opentiktok E/AndroidRuntime: FATAL EXCEPTION: EngineThread
    Process: com.galix.opentiktok, PID: 17579
    java.lang.RuntimeException: Error creating program.
        at com.galix.avcore.util.GLUtil.createAndLinkProgram(GLUtil.java:96)
        at com.galix.avcore.util.GLUtil.loadProgram(GLUtil.java:116)
        at com.galix.avcore.render.filters.BaseFilter.open(BaseFilter.java:109)
        at com.galix.opentiktok.dp.DPFastRender.open(DPFastRender.java:66)
        at com.galix.avcore.avcore.AVEngine.onDrawFrame(AVEngine.java:337)
        at com.galix.avcore.avcore.AVEngine.lambda$createEngineDaemon$0$AVEngine(AVEngine.java:559)
        at com.galix.avcore.avcore.-$$Lambda$AVEngine$gZDBoaaRIlbWbwOdefk7aUl7R9s.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

最近在学习音视频方面，希望作者代码能早点跑起来...

**Comment by galis** [comment]
> 

你好，谢谢你的关注。由于是开源项目，我这边没有做很多兼容性的测试。能说下手机型号和系统版本号吗？将有利于我快速定位问题。

**Comment by fansangg** [comment]
> 你好，谢谢你的关注。由于是开源项目，我这边没有做很多兼容性的测试。能说下手机型号和系统版本号吗？将有利于我快速定位问题。

手上这台设备是HUAWEI的P30（VOG-AL00），Android10版本

**Comment by galis** [comment]
> > 你好，谢谢你的关注。由于是开源项目，我这边没有做很多兼容性的测试。能说下手机型号和系统版本号吗？将有利于我快速定位问题。
> 
> 手上这台设备是HUAWEI的P30（VOG-AL00），Android10版本

好的。晚点我尝试下。

**Comment by galis** [comment]
> 选择cache/composite下的视频文件

你好，你可以更新代码，依然选择cache/composite下的视频文件再次尝试。之前的问题是因为getCurrentWindowMetrics 在Android11才能生效！

另外录屏按钮的功能暂时不可用。我用来测试的。

**Comment by fansangg** [comment]
大佬，我打开视频到编辑页，页面是黑色的，但是也没发现哪报错，改天我找个高版本的手机试试吧

**Comment by galis** [comment]
可以再试一下。
