### ISSUE TITLE
选择视频后，报错 手机型号： HUAWEI SCMR-W09    系统版本：Android 10

### ISSUE THREAD

**Issue by gionlime** [galis/OpenTikTok#5]
2022-05-10 09:46:14.817 31429-31670/com.galix.opentiktok E/GLUtil: Shader error: 0:22: S0001: No matching overload for function 'filterTexture2D' found
    #version 300 es
    #extension GL_OES_EGL_image_external_essl3 : require
    precision mediump float;
    in vec2 vTextureCoord;
    out vec4 vFragColor;
    uniform vec3 bgColor;
    uniform mat3 textureMat;
    uniform bool isOes;
    uniform sampler2D inputImageTexture;
    uniform samplerExternalOES oesImageTexture;
    
    vec4 filterTexture2D(sampler2D targetTexture, vec2 coord){
        if (coord.x < 0.0||coord.x>1.0||coord.y<0.0||coord.y>1.0) {
            return vec4(bgColor, 1.0);
        }
        return texture(targetTexture, coord);
    }
    
    void main(){
        vec2 coord = (textureMat*vec3(vTextureCoord, 1.0)).xy;
        if (isOes){
            vFragColor = filterTexture2D(oesImageTexture, vec2(coord.x, 1.0-coord.y));
            return;
        }
        vFragColor = filterTexture2D(inputImageTexture, coord);
    }
2022-05-10 09:46:14.817 31429-31670/com.galix.opentiktok E/GLUtil: Error compiling program: Link failed because of missing fragment shader.
2022-05-10 09:46:14.817 31429-31670/com.galix.opentiktok E/AndroidRuntime: FATAL EXCEPTION: EngineThread
    Process: com.galix.opentiktok, PID: 31429
    java.lang.RuntimeException: Error creating program.
        at com.galix.avcore.util.GLUtil.createAndLinkProgram(GLUtil.java:107)
        at com.galix.avcore.util.GLUtil.loadProgram(GLUtil.java:127)
        at com.galix.avcore.render.filters.BaseFilter.open(BaseFilter.java:115)
        at com.galix.avcore.render.ScreenRender.open(ScreenRender.java:53)
        at com.galix.avcore.avcore.AVEngine.handleSurfaceChange(AVEngine.java:767)
        at com.galix.avcore.avcore.AVEngine.lambda$createEngineDaemon$0$AVEngine(AVEngine.java:695)
        at com.galix.avcore.avcore.-$$Lambda$AVEngine$gZDBoaaRIlbWbwOdefk7aUl7R9s.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.os.HandlerThread.run(HandlerThread.java:67)

![image](https://user-images.githubusercontent.com/91245043/167526306-3b1f1c35-06e7-4faf-b45f-f0e85126d3af.png)

**Comment by galis** [comment]
已经修复。可以再试一下。
