### ISSUE TITLE
选择视频打不开

### ISSUE THREAD

**Issue by liyihuanx** [galis/OpenTikTok#8]
我选择视频页面是空白的，我以为是我文件太多加载不出来，然后修改了一下代码让MP4List直接add在sdcard下的testfile.mp4，打钩后一直转圈圈是咋回事呢，求解

**Comment by galis** [comment]
麻烦发下手机型号+系统版本+相关日志。

**Comment by liyihuanx** [comment]
手机型号：OPPO R9sk
系统版本：Android6
出错语句：if (Integer.parseInt(mediaMetadataRetriever.extractMetadata(MediaMetadataRetriever.METADATA_KEY_VIDEO_FRAME_COUNT)) > 0) 
相关日志：java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
        at com.galix.opentiktok.ui.VideoPickActivity$1.getItemCount(VideoPickActivity.java:121)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4044)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3849)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)

**Comment by liyihuanx** [comment]
> 麻烦发下手机型号+系统版本+相关日志。

手机型号：OPPO R9sk
系统版本：Android6
出错语句：if (Integer.parseInt(mediaMetadataRetriever.extractMetadata(MediaMetadataRetriever.METADATA_KEY_VIDEO_FRAME_COUNT)) > 0) 
相关日志：java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
        at com.galix.opentiktok.ui.VideoPickActivity$1.getItemCount(VideoPickActivity.java:121)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4044)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3849)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)

**Comment by liyihuanx** [comment]
> 麻烦发下手机型号+系统版本+相关日志。

手机型号：OPPO R9sk
系统版本：Android6

出错语句：
if(Integer.parseInt(mediaMetadataRetriever.extractMetadata(MediaMetadataRetriever.METADATA_KEY_VIDEO_FRAME_COUNT)) > 0)

相关日志：
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
at com.galix.opentiktok.ui.VideoPickActivity$1.getItemCount(VideoPickActivity.java:121)
at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4044)
at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3849)
at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)

**Comment by galis** [comment]
把文件放在/data/data/com.galix.opentiktok/cache目录下试试，/sdcard/目录下Android高版本好像有权限问题。

**Comment by liyihuanx** [comment]
> 把文件放在/data/data/com.galix.opentiktok/cache目录下试试，/sdcard/目录下Android高版本好像有权限问题。

尝试过呢，也没有用....

**Comment by liudoge66** [comment]
高版本的Android限制很大，我自己尝试了很多方法也没办法读取到原本手机内部存储的视频
没办法，没有条件创造条件，我调用手机自带的相机进行拍摄，然后更改存储路径到SD卡中，这才能读取到视频信息
这样一来问题就又来了，我应该怎么导出视频到手机内部而不是软件内呢？
这个问题和其他软件例如B站或者抖音一样，下载的视频是不能直接在手机相册中读取到的，都被封装在了应用内部
这明显不符合软件的原本用意，希望能有大神指点一二
